name: Build pmos
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      set_Channel:
        description: "Channel"
        required: true
        default: "edge"
      set_Device:
        description: "Device"
        required: true
        default: "xiaomi"
      set_code:
        description: "code"
        required: true
        default: "gemini"
      set_ui:
        description: "ui"
        required: true
        default: "gnome-mobile"
env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Installation pmbootstrap
        run: |
          
          sudo apt update
          sudo apt install git 
          git clone https://gitlab.com/postmarketOS/pmbootstrap.git
          cd pmbootstrap
          git checkout 2.3.x
          
          mkdir -p ~/.local/bin
          ln -s "$PWD/pmbootstrap.py" ~/.local/bin/pmbootstrap
          PATH="$HOME/.local/bin:$PATH"
          pmbootstrap --version
      - name: build
        run: |
          echo -e "\n${{ github.event.inputs.set_Channel }}\n${{ github.event.inputs.set_Channel }}\n${{ github.event.inputs.set_code }}\nwpa_supplicant\n${{ github.event.inputs.set_ui }}\n\n\n\n\n\n\n" | ./script.sh
          # pmbootstrap init <<EOF
          
          # ${{ github.event.inputs.set_Channel }}
          # ${{ github.event.inputs.set_Device }}
          # ${{ github.event.inputs.set_code }}
          # wpa_supplicant
          # ${{ github.event.inputs.set_ui }}







          
          # EOF

          pmbootstrap install --android-recovery-zip --recovery-install-partition=data <<EOF

          1234
          1234
          EOF
          pmbootstrap export
          zip_path=$(readlink -f /tmp/postmarketOS-export/pmos-*.zip)
          echo "Zip path: $zip_path"
          echo "::set-output name=zip_path::$zip_path"
          
      - name: Upload zip
        uses: actions/upload-artifact@v3
        with:
          name: pmos
          path: ${{ steps.get_zip_path.outputs.zip_path }}


