
name: Build mpv static
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      set_git_repo:
        description: "aarch64"
        required: true
        default: "mpv"


env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Compile
        id: compile
        run: |
          sudo mkdir -p /media/ramdisk/mpv-build
          sudo mkdir -p /home/pintcat/ubin
          sudo apt update
          sudo apt install -y meson ninja-build yasm autoconf autoconf-archive libtool pkgconf pkg-config python3-docutils spirv-cross wayland-protocols debhelper-compat libfreetype-dev libfribidi-dev libharfbuzz-dev libfontconfig-dev libjpeg-dev libx11-dev libarchive-dev libasound2-dev libass-dev libavcodec-dev libavdevice-dev libavfilter-dev libavformat-dev libavutil-dev libbluray-dev libcaca-dev libcdio-dev libcdio-paranoia-dev libdrm-dev libdvdnav-dev libegl-dev libffmpeg-nvenc-dev libgbm-dev libgl-dev libjack-dev liblcms2-dev liblua5.2-dev libmujs-dev libpipewire-0.3-dev libplacebo-dev libpulse-dev librubberband-dev libsdl2-dev libsixel-dev libspirv-cross-c-shared-dev libswscale-dev libuchardet-dev libva-dev libvdpau-dev libvulkan-dev libwayland-dev libxinerama-dev libxkbcommon-dev libxpresent-dev libxrandr-dev libxss-dev libxv-dev libzimg-dev
          #export CROSS_COMPILE=aarch64-linux-gnu-
          #export ARCH=aarch64
          sudo sh do-mpv.sh
          pwd
          ls -ltrh
          
          echo "::set-output name=status::success"
          

      - name: Upload file
        uses: actions/upload-artifact@v3
        with:
          name: mpv-aarch64
          path: /home/pintcat/ubin/*

      - name: Upload image to Release
        uses: ncipollo/release-action@main
        if: steps.compile.outputs.status == 'success' && !cancelled()
        with:
          tag: mpv_aarch64_${{ env.COMPILE_STARTINGTIME }}
          artifacts: /home/pintcat/ubin/*
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            This is mpv static ${{ env.LINUX_GITURL }}
