name: Build OnePlus 6T (Ubuntu Jammy)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      KERNEL_DIR: linux-sdm845-6.16-845
      CONFIG_FILE: .config
      KERNEL_IMAGE: vmlinux
      MODULES_DIR: modules
      MODULES_DIR_UBUNTU: modules-ubuntu
      IMAGE_DIR: images
      INITRAMFS: initrd.img
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y git make gcc-arm-linux-gnueabihf bc kmod \
            libssl-dev libelf-dev cpio flex bison bc wget rsync unzip \
            python3 python3-pip libncurses5-dev libncursesw5-dev gnupg2 \
            pkg-config libssl-dev libelf-dev libncurses5-dev libncursesw5-dev \
            libudev-dev libsystemd-dev libudev-dev libusb-1.0-0-dev \
            libudev-dev libsystemd-dev libudev-dev

      # ------------------------------------------------------------------
      # 这里的所有 `run:` 语句都是 shell 脚本，保持不变，下面仅修正 heredoc
      # ------------------------------------------------------------------
      - name: Install tty console service
        run: |
          wget -O ttygs0-console.sh ${{ env.TTY_SCRIPT }}
          sudo chmod +x ttygs0-console.sh
          sudo mv ttygs0-console.sh /usr/local/bin/
          sudo tee ubuntu/etc/systemd/system/oneplus6t-console.service >/dev/null <<'EOF'
          [Unit]
          Description=OnePlus6T USB Console Service
         
