
name: Build mpv static
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      set_git_repo:
        description: "aarch64"
        required: true
        default: "mpv"


env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-24.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Compile
        id: compile
        run: |
          sudo mkdir -p /media/ramdisk/mpv-build
          sudo mkdir -p /home/pintcat/ubin
          sudo apt update
          sudo apt install -y meson libfreetype6-dev libfreetype-dev libfribidi-dev

          export CROSS_COMPILE=aarch64-linux-gnu-
          export ARCH=arm64
          sudo sh do-mpv.sh
          pwd
          ls -ltrh
          
          echo "::set-output name=status::success"
          

      - name: Upload file
        uses: actions/upload-artifact@v3
        with:
          name: debian-linux
          path: /workdir/*

      - name: Upload image to Release
        uses: ncipollo/release-action@main
        if: steps.compile.outputs.status == 'success' && !cancelled()
        with:
          tag: Linux_Kernel_${{ env.COMPILE_STARTINGTIME }}
          artifacts: /workdir/*
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            This is mpv static ${{ env.LINUX_GITURL }}
