
name: Download pmos oneplus6t
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      set_git_repo:
        description: "aarch64"
        required: true
        default: "fedora"


env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Compile
        id: compile
        run: |
          curl -LO "hhttps://images.postmarketos.org/bpo/v25.06/oneplus-fajita/phosh/20250621-1248/20250621-1248-postmarketOS-v25.06-phosh-25-oneplus-fajita.img.xz"
          pwd
          ls -ltrh
          
          echo "::set-output name=status::success"
          

      - name: Upload file
        uses: actions/upload-artifact@v4
        with:
          name: pmos-SDM845
          path: ./*.img.xz

      - name: Upload image to Release
        uses: ncipollo/release-action@main
        if: steps.compile.outputs.status == 'success' && !cancelled()
        with:
          tag: pmos-SDM845_${{ env.COMPILE_STARTINGTIME }}
          artifacts: ./*.img.xz
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            This is pmos-SDM845_${{ env.LINUX_GITURL }}
