
name: Download athbe files
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      set_git_repo:
        description: "aarch64"
        required: true
        default: "athbe"


env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Compile
        id: compile
        run: |
          #curl -LO "https://github.com/fedora-remix-mobility/fedora-kiwi-descriptions/releases/download/2025-04-04/Fedora-SDM845-Remix.tar.xz"
          #wget "https://cloud.athbe.cn/f/6nSr/firmware.tar.gz"
          #wget  "http://kaixinit.com/wp-content/uploads/2025/09/firmware.tar.gz"
          #wget https://sourceforge.net/projects/waydroid/files/images/system/lineage/waydroid_arm64/lineage-20.0-20250809-GAPPS-waydroid_arm64-system.zip
          #wget https://sourceforge.net/projects/waydroid/files/images/vendor/waydroid_arm64/lineage-20.0-20250809-MAINLINE-waydroid_arm64-vendor.zip
          wget "http://[2409:8a55:3312:5f30:f0c7:a851:f195:4b98]:8000/sailfishos-5.0.0.43-20241218-mido-alpha1.zip"
          pwd
          ls -ltrh
          
          
          echo "::set-output name=status::success"
          

      - name: Upload file
        uses: actions/upload-artifact@v4
        with:
          name: sailfishos-5.0.0.43-20241218-mido-alpha1.zip
          path: ./sailfishos-5.0.0.43-20241218-mido-alpha1.zip
      - name: Upload image to Release
        uses: ncipollo/release-action@main
        if: steps.compile.outputs.status == 'success' && !cancelled()
        with:
          tag: sdm845.config_${{ env.COMPILE_STARTINGTIME }}
          artifacts: ./sailfishos-5.0.0.43-20241218-mido-alpha1.zip
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            This is sailfishos-5.0.0.43-20241218-mido-alpha1.zip_${{ env.LINUX_GITURL }}
