name: Build archlinux with kupfer for sdm845-oneplus-fajita
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      set_example:
        description: "sdm845-oneplus-fajita"
        required: true
        default: "none"
  
env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      

      - name: Installation python3 docker.io git
        run: |
          sudo apt update
          #sudo apt install python3 docker.io git
          sudo apt search gcc12
          sudo apt install wget gcc-12 gcc-12-aarch64-linux-gnu
          
          
          

      - name: kupferbootstrap-build
        run: |
          sudo usermod -aG docker "$(whoami)"
          git clone -b dev https://gitlab.com/kupfer/kupferbootstrap
          cd kupferbootstrap
          pip3 install -r requirements.txt --break-system-packages
          kupferbootstrap config init -N
          kupferbootstrap config profile init oneplus-fajita
          wget https://github.com/gmicroul/action_for_pmos/raw/refs/heads/main/kupferbootstrap.toml
          pwd
          ls -ltrh
          kupferbootstrap image build oneplus-fajita
          pwd
          ls -ltrh
          zip_path=$(readlink -f *-fajita)
          echo "Zip path: $zip_path"
          echo "::set-output name=zip_path::$zip_path"
        id: get_zip_path
        
          
      - name: Upload zip
        uses: actions/upload-artifact@v4
        with:
          #name: pmos-${{ github.event.inputs.set_Device }}-${{ github.event.inputs.set_code }}-${{ github.event.inputs.set_ui }}
          name: nixos-${{ github.event.inputs.set_example }}
          path: ${{ steps.get_zip_path.outputs.zip_path }}/*

          
          
   
