name: Build Archlinux with kupferbootstrap for oneplus-fajita
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      set_flavour:
        description: "flavour"
        required: true
        default: "phosh"
  
env:
  TZ: Asia/Shanghai


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: sandervocke/setup-qemu-container@v1
          with:
            container: archlinux
            arch: amd64


        - name: Print architecture from within container
          shell: run-in-container.sh {0}
          run: |
            uname -a
            echo ::set-output name=uname::$(uname -a)
            pacman -Sy
            #pacman -S python python-pip docker docker-buildx git glibc wget --needed --noconfirm
            pacman -S python python-pip git glibc wget --needed --noconfirm
            rm /usr/lib/python3.12/EXTERNALLY-MANAGED
            echo "whoami=$(whoami)"
            #usermod -aG docker "$(whoami)"
            git clone -b dev https://gitlab.com/kupfer/kupferbootstrap
            cd kupferbootstrap
            pip3 install -r requirements.txt
            ln -s "$(pwd)/bin/kupferbootstrap" /usr/local/bin/
            kupferbootstrap --help
            pwd
            wget https://github.com/gmicroul/action_for_pmos/raw/refs/heads/main/kupferbootstrap.toml
            kupferbootstrap config init -N
            kupferbootstrap config profile init
            cp -r ./kupferbootstrap.toml /root/.config/kupfer/kupferbootstrap.toml
            kupferbootstrap image build oneplus-fajita

        - name: Get the output
        # Echo the `uname` output parameter from the `runcmd` step
          run: |
            echo "The uname output was ${{ steps.runcmd.outputs.uname }}"
