name: Build nixos for oneplus-fajita
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      set_example:
        description: "example"
        required: true
        default: "phosh"
  
env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Installation nix git
        run: |
          
          sudo apt update
          sudo apt install git nix
          
          

      - name: nix-build
        run: |
          echo -e "1234\n1234\n" | sudo passwd root
          echo -e "1234\n"|su
          git clone https://github.com/mobile-nixos/mobile-nixos.git
          cd mobile-nixos
          export NIXPKGS_ALLOW_UNFREE=1
          nix-build examples\/${{ github.event.inputs.set_example }}\/ --argstr device oneplus-fajita -A outputs.android-fastboot-images
   
